# Generated by Django 5.1.1 on 2024-10-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тег')),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заметка')),
                ('description', models.TextField()),
                ('when_to_note', models.DateTimeField()),
                ('created', models.DateField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='notion.tag')),
            ],
            options={
                'db_table': 'notions',
                'ordering': ['created'],
            },
        ),
    ]
