# Generated by Django 5.1.1 on 2024-10-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0003_alter_notion_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notion',
            unique_together={('title', 'created')},
        ),
    ]
