# Generated by Django 5.1.1 on 2024-10-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0004_alter_notion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notion',
            unique_together={('title', 'description', 'when_to_note', 'is_active')},
        ),
    ]
