# Generated by Django 5.1.1 on 2024-10-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0005_alter_notion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Тег'),
        ),
    ]
